package com.zzjz.zkemlink.mapper;

import com.zzjz.zkemlink.bean.PunchedCard;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import java.util.Date;
import java.util.List;

/**
 * PunchCardMapper
 * @author fgt
 */
@Component
public interface PunchCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_punch_card
     *
     * @mbg.generated
     */
    int insert(PunchedCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_punch_card
     *
     * @mbg.generated
     */
    int insertSelective(PunchedCard record);

    /**
     * 批量插入打卡信息.
     * @param res 打卡信息
     * @return 结果
     */
    int addPunchCardList(@Param("res") List<PunchedCard> res);

    /**
     * 删除指定日志之后的打卡数据.
     * @param date 日期
     * @return 结果
     */
    int delAfter(@Param("date") Date date);

    /**
     * 获取指定日期之后的打卡原始信息.
     * @param date 日期
     * @return 结果
     */
    List<PunchedCard> queryAfter(@Param("date") Date date);
}