package com.zzjz.zkemlink.mapper;

import com.zzjz.zkemlink.bean.ZkUserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import java.util.List;

/**
 * @author 彭鹏
 * @version 2017-10-16
 */
@Component(value = "ZkemUserMapper")
public interface ZkemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zkem_user
     *
     * @param record ZkUserInfo
     * @return int
     * @mbggenerated
     */
    int insert(ZkUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zkem_user
     *
     * @param record ZkUserInfo
     * @return int
     * @mbggenerated
     */
    int insertSelective(ZkUserInfo record);

    /**
     * 删除全部.
     */
    void deleteAll();

    /**
     * 批量新增.
     *
     * @param zkUserInfos zkUserInfos
     * @return 结果
     */
    int addAll(@Param("zkUserInfos") List<ZkUserInfo> zkUserInfos);

    /**
     * 获取全部.
     *
     * @return 全部用户信息
     */
    List<ZkUserInfo> getAll();

    /**
     * 通过姓名获取其考勤id.
     * @param name 姓名
     * @return id
     */
    String getUserIdByName(String name);
}